name: Update Hosts File

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
    # Allow manual trigger from GitHub UI

jobs:
  update-hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Generate hosts file
        run: |
          chmod +x ad_filter2hosts.sh
          ./ad_filter2hosts.sh

      - name: Update README with stats
        run: |
          echo "" >> hosts_filtered.txt
          LINE_COUNT=$(wc -l < hosts_filtered.txt)
          CURRENT_DATE=$(date '+%Y-%m-%d')

          # Create a metadata file with the stats
          echo "# Host File Information" > hosts_info.md
          echo "- Last updated: $CURRENT_DATE" >> hosts_info.md
          echo "- Total domains blocked: $LINE_COUNT" >> hosts_info.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add hosts_filtered.txt hosts_info.md

          # Only commit if there are changes
          git diff --cached --exit-code || git commit -m "Update hosts file - $(date '+%Y-%m-%d')" 
          git push
